#pragma once
#define SYS_PSB_MOUSE_HIDE   TP_SPSB,0








#define SYS_PSW_INPUT_NUMBER_CURVAL TP_SPSW,1000,1   //64λ
#define SYS_PSW_INPUT_NUMBER_LOWERLMT TP_SPSW,1000   //64λ
#define SYS_PSW_INPUT_NUMBER_UPPERERLMT TP_SPSW,1000


